CREATE TABLE case_person (
    person_id INTEGER NOT NULL,
    case_id INTEGER NOT NULL,
    cac_id SMALLINT NOT NULL,
    age INTEGER,
    age_unit VARCHAR(20),
    address_line_1 VARCHAR(200),
    address_line_2 VARCHAR(200),
    city VARCHAR(20),
    state_abbr VARCHAR(2),
    zip VARCHAR(20),
    cell_phone_number VARCHAR(200),
    home_phone_number VARCHAR(200),
    work_phone_number VARCHAR(200),
    custody BOOLEAN,
    education_level_id INTEGER,
    income_level_id INTEGER,
    marital_status_id INTEGER,
    relationship_id INTEGER,
    role_id INTEGER,
    same_household BOOLEAN,
    school_or_employer VARCHAR(200),
    victim_status_id INTEGER,
    FOREIGN KEY(person_id) REFERENCES person(person_id),
    FOREIGN KEY(case_id) REFERENCES cac_case(case_id),
    FOREIGN KEY(cac_id) REFERENCES child_advocacy_center(cac_id),
    PRIMARY KEY (person_id, case_id)
);