CREATE TABLE case_person (
    person_id INTEGER NOT NULL,
    case_id INTEGER NOT NULL,
    cac_id SMALLINT NOT NULL,
    age INTEGER,
    age_unit VARCHAR(20),
    addr_line_1 VARCHAR(200),
    addr_line_2 VARCHAR(200),
    city VARCHAR(20),
    state_abbr VARCHAR(2),
    zip_code VARCHAR(20),
    cell_phone VARCHAR(200),
    home_phone VARCHAR(200),
    work_phone VARCHAR(200),
    school_or_employer VARCHAR(200),
    custody BOOLEAN,
    education_level VARCHAR(200),
    income_level VARCHAR(200),
    marital_status VARCHAR(200),
    relationship VARCHAR(200),
    case_role VARCHAR(200),
    same_household BOOLEAN,
    victim_status_id INTEGER,
    FOREIGN KEY(person_id) REFERENCES person(person_id),
    FOREIGN KEY(case_id) REFERENCES cac_case(case_id),
    FOREIGN KEY(cac_id) REFERENCES child_advocacy_center(cac_id),
    FOREIGN KEY(state_abbr) REFERENCES state_table(state_abbr),
    PRIMARY KEY (person_id, case_id)
);