CREATE TABLE case_mh_session_log_enc (
    cac_id SMALLINT NOT NULL,
    case_id INTEGER NOT NULL,
    case_mh_session_id INTEGER PRIMARY KEY,
    comments VARCHAR(200),
    start_time VARCHAR(20),
    end_time VARCHAR(20),
    intervention_id INTEGER,
    location_id INTEGER,
    onsite BOOLEAN,
    provider_agency_id INTEGER,
    provider_employee_id INTEGER,
    session_date DATE NOT NULL,
    session_status_id INTEGER NOT NULL,
    session_type_id INTEGER,
    recurring BOOLEAN,
    recurring_fre VARCHAR(20),
    recurring_duration INTEGER,
    recurring_duration_unit VARCHAR(255),
    FOREIGN KEY(cac_id) REFERENCES child_advocacy_center(cac_id),
    FOREIGN KEY(case_id) REFERENCES cac_case(case_id),
    FOREIGN KEY(provider_agency_id) REFERENCES cac_agency(agency_id),
    FOREIGN KEY(provider_employee_id) REFERENCES employee(employee_id)
);