CREATE TABLE case_mh_session (
    case_mh_session_id INTEGER PRIMARY KEY,
    cac_id SMALLINT NOT NULL,
    case_id INTEGER NOT NULL,
    session_date DATE NOT NULL,
    session_type VARCHAR(200),
    session_status VARCHAR(200) NOT NULL,
    session_start_time VARCHAR(20),
    session_end_time VARCHAR(20),
    intervention_id INTEGER,
    session_location VARCHAR(200),
    onsite BOOLEAN,
    provider_agency_id INTEGER,
    provider_employee_id INTEGER,
    recurring BOOLEAN,
    recurring_frequency VARCHAR(20),
    recurring_duration INTEGER,
    recurring_duration_unit VARCHAR(200),
    comments VARCHAR(200),
    FOREIGN KEY(cac_id) REFERENCES child_advocacy_center(cac_id),
    FOREIGN KEY(case_id) REFERENCES cac_case(case_id),
    FOREIGN KEY(provider_agency_id) REFERENCES cac_agency(agency_id),
    FOREIGN KEY(provider_employee_id) REFERENCES employee(employee_id)
);