INSERT INTO case_person (
    person_id,
    case_id,
    cac_id,
    age,
    age_unit,
    address_line_1,
    address_line_2,
    city,
    state_abbr,
    zip,
    cell_phone_number,
    home_phone_number,
    work_phone_number,
    custody,
    education_level_id,
    income_level_id,
    marital_status_id,
    relationship_id,
    role_id,
    same_household,
    school_or_employer,
    victim_status_id
) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);