INSERT INTO case_person (
    person_id,
    case_id,
    cac_id,
    age,
    age_unit,
    addr_line_1,
    addr_line_2,
    city,
    state_abbr,
    zip_code,
    cell_phone,
    home_phone,
    work_phone,
    school_or_employer,
    custody,
    education_level,
    income_level,
    marital_status,
    relationship,
    case_role,
    same_household,
    victim_status_id
) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);